def apply_theme(window):
    window.setStyleSheet(
        "QWidget { background: #f3efe6; color: #111111; }"
        "QLabel { font-size: 10pt; }"
        "QDateEdit, QSpinBox {"
        "  background: #ffffff;"
        "  padding: 6px 8px;"
        "  border: 1px solid #1f1f1f;"
        "  border-radius: 6px;"
        "}"
        "QComboBox {"
        "  background: #ffffff;"
        "  padding: 6px 8px;"
        "  border: 1px solid #1f1f1f;"
        "  border-radius: 6px;"
        "}"
        "QTextEdit {"
        "  background: #ffffff;"
        "  border: 1px solid #1f1f1f;"
        "  border-radius: 6px;"
        "}"
        "QLineEdit {"
        "  background: #ffffff;"
        "  border: 1px solid #1f1f1f;"
        "  border-radius: 6px;"
        "  padding: 6px 8px;"
        "  min-height: 28px;"
        "}"
        "QListWidget {"
        "  background: #ffffff;"
        "  border: 1px solid #1f1f1f;"
        "  border-radius: 6px;"
        "}"
        "QPushButton {"
        "  background: #111111;"
        "  color: #ffffff;"
        "  padding: 8px 12px;"
        "  border-radius: 6px;"
        "}"
        "QPushButton:hover {"
        "  background: #1c1c1c;"
        "}"
        "QPushButton:pressed {"
        "  background: #000000;"
        "}"
        "QComboBox:hover, QLineEdit:hover, QTextEdit:hover, QListWidget:hover {"
        "  border: 1px solid #6b655c;"
        "}"
    )
    window.notes_panel.setStyleSheet(
        "QWidget { background: #ffffff; color: #111111; }"
        "QLabel { font-size: 10pt; }"
        "#detailLabel { color: #4b4b4b; }"
        "QTextEdit {"
        "  background: #ffffff;"
        "  color: #111111;"
        "  border: 1px solid #d3cbbb;"
        "  border-radius: 8px;"
        "}"
        "QLineEdit {"
        "  background: #ffffff;"
        "  color: #111111;"
        "  border: 1px solid #d3cbbb;"
        "  border-radius: 8px;"
        "  padding: 6px 8px;"
        "  min-height: 28px;"
        "}"
        "QListWidget {"
        "  background: #ffffff;"
        "  border: none;"
        "}"
        "#detailPanel {"
        "  background: #faf6ee;"
        "  border: 1px solid #e1d8c8;"
        "  border-radius: 10px;"
        "}"
        "#noteItem {"
        "  background: #ffffff;"
        "  border: 1px solid #e1d8c8;"
        "  border-radius: 10px;"
        "}"
        "#noteItem:hover {"
        "  background: #fbf7f0;"
        "  border: 1px solid #cbbdac;"
        "}"
        "#noteDateBox {"
        "  background: #9c2f1d;"
        "  border: 1px solid #6f1f14;"
        "  border-radius: 8px;"
        "  min-width: 64px;"
        "  min-height: 64px;"
        "}"
        "#noteMonth {"
        "  color: #ffffff;"
        "  background: transparent;"
        "  font-size: 8pt;"
        "  letter-spacing: 1px;"
        "}"
        "#noteDay {"
        "  color: #ffffff;"
        "  background: transparent;"
        "  font-size: 18pt;"
        "  font-weight: bold;"
        "}"
        "#noteTitle {"
        "  color: #111111;"
        "  font-weight: bold;"
        "  padding-top: 2px;"
        "}"
        "#noteSubtitle {"
        "  color: #6a6358;"
        "  font-size: 9pt;"
        "}"
        "QPushButton {"
        "  background: #1d2b3a;"
        "  color: #ffffff;"
        "  padding: 8px 10px;"
        "  border-radius: 10px;"
        "  margin: 0 2px;"
        "}"
        "QPushButton:hover {"
        "  background: #23384c;"
        "}"
        "QPushButton:pressed {"
        "  background: #15202c;"
        "}"
        "QPushButton#dangerButton {"
        "  background: #a33a2a;"
        "}"
        "QPushButton#dangerButton:hover {"
        "  background: #b74432;"
        "}"
    )
